### PR TITLE
Damage to drains

### PR DESCRIPTION
**Pull request by ChristyMorgan**
I made a decision tree based on damage to drains. I got the information from the Citizens Advice website. If you have any feedback that would be great as I would like to do a few more!

### CODE REVIEW

**Comment by amyconroy** [comment]
Really well done Christy! Thank you for your contribution, feel free to say hello on the discussion board :)

**Comment by ChristyMorgan** [comment]
Hi Amy,

Sorry, this is very out of the blue but my future employer would like a reference from OpenTenancy as I listed it on my CV. I think they just want to check I have contributed, however I am not sure if you do references or what details I would even give them?

Kind regards
Christy
________________________________

**Comment by amyconroy** [comment]
> Hi Amy, Sorry, this is very out of the blue but my future employer would like a reference from OpenTenancy as I listed it on my CV. I think they just want to check I have contributed, however I am not sure if you do references or what details I would even give them? Kind regards Christy
> […](#)
> ________________________________ From: Amy Conroy ***@***.***> Sent: 18 December 2020 20:10 To: open-tenancy/opentenancy_law ***@***.***> Cc: ChristyMorgan ***@***.***>; Author ***@***.***> Subject: Re: [open-tenancy/opentenancy_law] Damage to drains (#22) Really well done Christy! Thank you for your contribution, feel free to say hello on the discussion board :) — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fopen-tenancy%2Fopentenancy_law%2Fpull%2F22%23issuecomment-748296203&data=04%7C01%7C%7C5f5ad54b3e91401d107408d8a39102ad%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637439190555906907%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=E2h2uNXSRw8gAt%2BY5ZbaW2lN6XdubMjfbvSE5jAOiKM%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FASBEILNK545MDPGDEQNMO2TSVOZMRANCNFSM4VBSPMZA&data=04%7C01%7C%7C5f5ad54b3e91401d107408d8a39102ad%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637439190555916903%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=G4qKUaAoiwh4moQzdB8IXOlVb5Y%2B%2FabdcASdUJngS3I%3D&reserved=0>.

Hi Cristy, apologies this ended up in my spam. A link to the merge request is the proof you can provide that you contributed! :) (So a link to this thread).

**Comment by ChristyMorgan** [comment]
Hi Amy,

Thank you very much!

Kind regards
Christy

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Pull request merged**
